<?php
/**
 * Created by PhpStorm.
 * User: DongLiu
 * Date: 2018/11/3
 * Time: 10:33
 */

namespace home\models;


use Yii;
use yii\base\Model;
use yii\bootstrap\Html;

class PasswordResetRequestForm extends Model
{
    public $email;

    public function rules()
    {
        return [
            ['email','filter','filter'=>'trim'],
            ['email','required'],
            ['email','email'],
            ['email','exist',
                'targetClass'=>'\home\models\User',
                'filter'=>['status'=>User::STATUS_ACTIVE],
                'message'=>'邮箱未注册'
            ]
        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function sendEmail()
    {
        $user=User::findOne([
           'status'=>User::STATUS_ACTIVE,
           'email'=>$this->email
        ]);
        if(!$user){
            return false;
        }
        if(!User::isPasswordResetTokenValid($user->password_reset_token)){
            $user->generatePasswordResetToken();
        }
        if (!$user->save()){
            return false;
        }
        $resetLink=Yii::$app->urlManager->createAbsoluteUrl(['site/reset-password','token'=>$user->password_reset_token]);
        return Yii::$app
            ->mailer
            ->compose()
            ->setFrom(['15130503571@163.com'=>'liudong.com'])
            ->setTo($this->email)
            ->setSubject('请改密码'.Yii::$app->name)
            ->setHtmlBody(Html::a(Html::encode($resetLink),$resetLink))
            ->send();

    }

}