<?php
/**
 * Created by PhpStorm.
 * User: DongLiu
 * Date: 2018/11/2
 * Time: 22:00
 */

namespace home\widgets;


use yii\base\Widget;

class Alert extends Widget
{
    public function run()
    {

        $flashes=\Yii::$app->session->getAllFlashes();
        foreach ($flashes as $k=>$v){
            //echo $v;
            //         弹窗报错
            $message[]=$k;
            $message[]=$v;
            return $this->render('alterView',['message'=>$message]);
        }
        //parent::run(); // TODO: Change the autogenerated stub
    }

}